### ISSUE TITLE
[Feature] - Script for tracking down Analytics

### ISSUE THREAD

**Issue by MrBaptista69** [CryptoBlades/cryptoblades#1786]
### Prerequisites

- [X] I checked to make sure that this feature has not already been filed
- [X] I'm reporting this information to the correct repository
- [X] I understand enough about this issue to complete a comprehensive document

### Describe the feature and its requirements

Analytics Wishlist
*Analytics should include specific data from each chain as well as a summed total unless stated otherwise

- **Characters**

      Number of gen1 characters minted
      Number of gen1 characters burned
      Level distribution of gen1 characters
      The power distribution of gen1 characters
      Number of gen1 characters in garrisons
      Number of gen2 characters minted
      Number of gen2 characters burned
      Level distribution of gen2 characters
      The power distribution of gen2 characters
      Number of gen2 characters in garrisons
      

- **Weapons**

      Number of weapons forged
      Number of weapons burned
      Star distribution of available weapons
      

- **Adventure**

      Number of combats
      Number of combats won
      Amount of earnings
      Distribution of earnings
- **Raids**
      Number of raiders
      Distribution of rewards

- **PvP**

      Number of entrants in the arena
      Number of battles in the arena

- **Quests**

      Number of wallet quests completed
      Number of character quests completed

- **Bazaar**

      How many gen1 characters listed
      How many gen1 characters sold
      How many gen2 characters listed
      How many gen2 characters sold
      How many weapons listed
      How many weapons sold
      How many shields listed
      How many shields sold
      How many T1, T2, and T3 lands are sold from the SKILL Shop
      How many of the other items listed in the SKILL Shop are sold

- **Bridge**

      How many gen1 characters are bridged
      How many gen2 characters are bridged
      How many weapons are bridged
      How many shields are bridged
      How much SKILL is bridged
      How much VALOR is bridged

1. It would be good to have statistics on how many are bridged from a particular chain as well as to a specific chain

2. It would also be good to have statistics that can isolate specific chain-to-chain interactions
For example, being able to toggle Heco -> BNB weapons or CSC -> Polygon characters or SKALE -> BNB SKILL

- **Treasury**

      Rewards paid out
      Multi-farm amounts remaining

- **General CryptoBlades**

      Number of users (unique wallets)
      Number of transactions

### Is your feature request related to an existing issue? Please describe.

nOPE

### Is there anything stopping this feature being completed?

n/a

### Describe alternatives you've considered

None
